### ISSUE TITLE
Add jquery.tocify.min.js to the Cloudflare CDN

### ISSUE THREAD

**Issue by natea** [appsembler/paascheatsheet#1]
tocify is here: http://gregfranko.com/jquery.tocify.js/

add it to here: https://github.com/cdnjs/cdnjs

**Comment by gfranko** [comment]
I'll request Tocify to be added to CDN.js.

**Comment by natea** [comment]
Great, thanks!

On Sun, Apr 7, 2013 at 3:04 PM, Greg Franko notifications@github.comwrote:

> I'll request Tocify to be added to CDN.js.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/appsembler/paascheatsheet/issues/1#issuecomment-16021238
> .

## 

nate@appsembler.com
+1 (617) 517-4953
http://twitter.com/natea | http://linkedin.com/in/natea

**Comment by thraxil** [comment]
Archiving this project. Please let me know if it's still active and should be unarchived.
